### ISSUE TITLE
Cannot run demo on iMX6 with Yocto

### ISSUE THREAD

**Issue by vlisivka** [canselcik/libremarkable#21]
Because of this error:

```
root@localhost:~# RUST_BACKTRACE=1 ./demo
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrUnaligned', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/cfdc84a009020c59e53e4039beae22eb59e41685/src/libcore/macros.rs:18
   9: <libremarkable::framebuffer::core::Framebuffer as libremarkable::framebuffer::FramebufferBase>::new
             at /rustc/cfdc84a009020c59e53e4039beae22eb59e41685/src/libcore/result.rs:800
             at src/framebuffer/core.rs:67
  10: libremarkable::appctx::ApplicationContext::new
             at src/appctx.rs:96
  11: demo::main
             at examples/demo.rs:673
  12: std::rt::lang_start::{{closure}}
             at /rustc/cfdc84a009020c59e53e4039beae22eb59e41685/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: main
  17: __libc_start_main
```

**Comment by canselcik** [comment]
Are you trying to daemonize the demo? I remember hitting a similar issue a while ago. It had to do with opening the FD to /dev/fb0 before or after the double-forking.

**Comment by vlisivka** [comment]
No, it was typo, sorry. It clearly visible that I just try to run demo on device.

What can be done to fix this problem with libremarkable?

**Comment by canselcik** [comment]
@vlisivka Looks like the following unwrap is failing:
```rust
        let mem_map = MemoryMap::new(
            frame_length,
            &[
                mmap::MapOption::MapReadable,
                mmap::MapOption::MapWritable,
                mmap::MapOption::MapFd(device.as_raw_fd()),
                mmap::MapOption::MapOffset(0),
                mmap::MapOption::MapNonStandardFlags(libc::MAP_SHARED),
            ],
        )
        .unwrap();
```
Do you have `/dev/fb0` on iMX6? If fb0 is placed elsewhere or named differently, that'd explain it.

Besides that I am assuming you aren't running the kernel that Remarkable Tablet ships with. You can compile it from source (it is found at https://github.com/reMarkable/linux)

The kernel module it builds with that's relevant to you is this one: https://github.com/reMarkable/linux/blob/zero-gravitas/drivers/video/fbdev/mxc/mxc_epdc_fb.c

Let me know how it goes for you.

**Comment by LinusCDE** [comment]
I guess this issue can be closed as well, @canselcik.

**Comment by LinusCDE** [comment]
Closing this, as it is ancient and likely not occurring and/or relevant today. If this happens again, feel free to open a new issue.
